Repository TravelLand/Travly_BE, pull requests merged in 2024-04, with the labels that each got.

#18 FEAT: 여행플랜 CRUD
  .gitignore
  src/main/java/com/travelland/TravellandApplication.java
  src/main/java/com/travelland/controller/PlanController.java
  src/main/java/com/travelland/docs/PlanControllerDocs.java
  src/main/java/com/travelland/domain/DayPlan.java
  src/main/java/com/travelland/domain/Member.java
  src/main/java/com/travelland/domain/Plan.java
  src/main/java/com/travelland/domain/UnitPlan.java
  src/main/java/com/travelland/dto/DayPlanDto.java
  src/main/java/com/travelland/dto/PlanDto.java
  src/main/java/com/travelland/dto/UnitPlanDto.java
  src/main/java/com/travelland/repository/DayPlanRepository.java
  src/main/java/com/travelland/repository/MemberRepository.java
  src/main/java/com/travelland/repository/PlanRepository.java
  src/main/java/com/travelland/repository/UnitPlanRepository.java
  src/main/java/com/travelland/service/PlanService.java
Labels: enhancement

#26 Feat: Features/signup 카카오 로그인 기능 구현
  build.gradle
  src/main/java/com/travelland/constant/Gender.java
  src/main/java/com/travelland/controller/MemberController.java
  src/main/java/com/travelland/controller/TestController.java
  src/main/java/com/travelland/docs/MemberControllerDocs.java
  src/main/java/com/travelland/docs/TestControllerDocs.java
  src/main/java/com/travelland/domain/Member.java
  src/main/java/com/travelland/domain/RefreshToken.java
  src/main/java/com/travelland/dto/MemberDto.java
  src/main/java/com/travelland/dto/MemberRequestDto.java
  src/main/java/com/travelland/global/config/RedisConfig.java
  src/main/java/com/travelland/global/config/RestTemplateConfig.java
  src/main/java/com/travelland/global/config/WebSecurityConfig.java
  src/main/java/com/travelland/global/dto/ResponseDto.java
  src/main/java/com/travelland/global/exception/GlobalControllerAdvice.java
  src/main/java/com/travelland/global/jwt/JwtUtil.java
  src/main/java/com/travelland/global/security/JwtAuthenticationFilter.java
  src/main/java/com/travelland/global/security/JwtAuthorizationFilter.java
  src/main/java/com/travelland/global/security/UserDetailsServiceImpl.java
  src/main/java/com/travelland/repository/MemberRepository.java
  src/main/java/com/travelland/repository/RefreshTokenRepository.java
  src/main/java/com/travelland/service/KakaoService.java
  src/main/resources/static/basic.js
  src/main/resources/templates/login.html
Labels: enhancement

#29 Feature/trip like scrap
  src/main/java/com/travelland/controller/TripController.java
  src/main/java/com/travelland/docs/TripControllerDocs.java
  src/main/java/com/travelland/domain/Trip.java
  src/main/java/com/travelland/domain/TripLike.java
  src/main/java/com/travelland/domain/TripScrap.java
  src/main/java/com/travelland/dto/TripDto.java
  src/main/java/com/travelland/global/exception/ErrorCode.java
  src/main/java/com/travelland/repository/TripLikeRepository.java
  src/main/java/com/travelland/repository/TripScrapRepository.java
  src/main/java/com/travelland/service/TripHashTagService.java
  src/main/java/com/travelland/service/TripLikeService.java
  src/main/java/com/travelland/service/TripScrapService.java
  src/main/java/com/travelland/service/TripService.java
Labels: enhancement

#30 Features/elastic
  build.gradle
  src/main/java/com/travelland/TravellandApplication.java
  src/main/java/com/travelland/constant/TripLocation.java
  src/main/java/com/travelland/controller/PlanController.java
  src/main/java/com/travelland/controller/TestController.java
  src/main/java/com/travelland/controller/TripSearchController.java
  src/main/java/com/travelland/docs/PlanControllerDocs.java
  src/main/java/com/travelland/document/TripSearchDoc.java
  src/main/java/com/travelland/domain/plan/DayPlan.java
  src/main/java/com/travelland/domain/plan/Plan.java
  src/main/java/com/travelland/domain/plan/PlanLike.java
  src/main/java/com/travelland/domain/plan/PlanScrap.java
  src/main/java/com/travelland/domain/plan/UnitPlan.java
  src/main/java/com/travelland/dto/DayPlanDto.java
  src/main/java/com/travelland/dto/PlanDto.java
  src/main/java/com/travelland/dto/TripSearchDto.java
  src/main/java/com/travelland/dto/UnitPlanDto.java
  src/main/java/com/travelland/global/config/ElasticsearchConfig.java
  src/main/java/com/travelland/repository/TripSearchRepository.java
  src/main/java/com/travelland/repository/es/CustomTripRepository.java
  src/main/java/com/travelland/repository/es/CustomTripRepositoryImpl.java
  src/main/java/com/travelland/repository/plan/DayPlanRepository.java
  src/main/java/com/travelland/repository/plan/PlanLikeRepository.java
  src/main/java/com/travelland/repository/plan/PlanRepository.java
  src/main/java/com/travelland/repository/plan/PlanScrapRepository.java
  src/main/java/com/travelland/repository/plan/UnitPlanRepository.java
  src/main/java/com/travelland/repository/plan/querydsl/CustomPlanLikeRepository.java
  src/main/java/com/travelland/repository/plan/querydsl/CustomPlanLikeRepositoryImpl.java
  src/main/java/com/travelland/repository/plan/querydsl/CustomPlanScrapRepository.java
  src/main/java/com/travelland/repository/plan/querydsl/CustomPlanScrapRepositoryImpl.java
  src/main/java/com/travelland/service/TripSearchService.java
  src/main/java/com/travelland/service/plan/PlanLikeService.java
  src/main/java/com/travelland/service/plan/PlanScrapService.java
  src/main/java/com/travelland/service/plan/PlanService.java
  src/main/resources/application.yml
  src/main/resources/static/es-mapping.json
  src/main/resources/static/es-setting.json
Labels: enhancement

#33 Features/data faker
  build.gradle
  src/main/java/com/travelland/dto/PlanDto.java
  src/main/java/com/travelland/service/KakaoService.java
  src/test/java/com/travelland/service/KakaoServiceTest.java
  src/test/java/com/travelland/service/plan/PlanServiceTest.java
Labels: enhancement

#38 FIX: Trip 성능 개선
  src/main/java/com/travelland/controller/TripController.java
  src/main/java/com/travelland/controller/TripSearchController.java
  src/main/java/com/travelland/docs/TripControllerDocs.java
  src/main/java/com/travelland/document/TripSearchDoc.java
  src/main/java/com/travelland/domain/trip/Trip.java
  src/main/java/com/travelland/domain/trip/TripHashtag.java
  src/main/java/com/travelland/domain/trip/TripImage.java
  src/main/java/com/travelland/domain/trip/TripLike.java
  src/main/java/com/travelland/domain/trip/TripScrap.java
  src/main/java/com/travelland/dto/TripDto.java
  src/main/java/com/travelland/dto/TripSearchDto.java
  src/main/java/com/travelland/repository/es/CustomTripRepository.java
  src/main/java/com/travelland/repository/es/CustomTripRepositoryImpl.java
  src/main/java/com/travelland/repository/trip/TripHashtagRepository.java
  src/main/java/com/travelland/repository/trip/TripImageRepository.java
  src/main/java/com/travelland/repository/trip/TripLikeRepository.java
  src/main/java/com/travelland/repository/trip/TripRedisRepository.java
  src/main/java/com/travelland/repository/trip/TripRepository.java
  src/main/java/com/travelland/repository/trip/TripScrapRepository.java
  src/main/java/com/travelland/repository/trip/TripSearchRepository.java
  src/main/java/com/travelland/repository/trip/querydsl/CustomTripLikeRepository.java
  src/main/java/com/travelland/repository/trip/querydsl/CustomTripLikeRepositoryImpl.java
  src/main/java/com/travelland/repository/trip/querydsl/CustomTripRepositoryV2.java
  src/main/java/com/travelland/repository/trip/querydsl/CustomTripRepositoryV2Impl.java
  src/main/java/com/travelland/repository/trip/querydsl/CustomTripScrapRepository.java
  src/main/java/com/travelland/repository/trip/querydsl/CustomTripScrapRepositoryImpl.java
  src/main/java/com/travelland/service/trip/TripImageService.java
  src/main/java/com/travelland/service/trip/TripLikeService.java
  src/main/java/com/travelland/service/trip/TripScrapService.java
  src/main/java/com/travelland/service/trip/TripSearchService.java
  src/main/java/com/travelland/service/trip/TripService.java
  src/main/resources/static/es-mapping.json
  src/test/java/com/travelland/service/KakaoServiceTest.java
  src/test/java/com/travelland/service/trip/TripServiceTest.java
Labels: bug

#39 FEAT: Plan 통합 조회 기능 구현
  src/main/java/com/travelland/TravellandApplication.java
  src/main/java/com/travelland/controller/PlanController.java
  src/main/java/com/travelland/docs/PlanControllerDocs.java
  src/main/java/com/travelland/dto/DayPlanDto.java
  src/main/java/com/travelland/dto/PlanDto.java
  src/main/java/com/travelland/service/trip/TripService.java
  src/main/resources/keystore.p12
Labels: enhancement

#40 Feature/test all
  src/main/java/com/travelland/TravellandApplication.java
  src/main/java/com/travelland/controller/PlanController.java
  src/main/java/com/travelland/controller/TripController.java
  src/main/java/com/travelland/controller/TripSearchController.java
  src/main/java/com/travelland/docs/PlanControllerDocs.java
  src/main/java/com/travelland/docs/TripControllerDocs.java
  src/main/java/com/travelland/document/TripSearchDoc.java
  src/main/java/com/travelland/domain/trip/Trip.java
  src/main/java/com/travelland/domain/trip/TripHashtag.java
  src/main/java/com/travelland/domain/trip/TripImage.java
  src/main/java/com/travelland/domain/trip/TripLike.java
  src/main/java/com/travelland/domain/trip/TripScrap.java
  src/main/java/com/travelland/dto/DayPlanDto.java
  src/main/java/com/travelland/dto/PlanDto.java
  src/main/java/com/travelland/dto/TripDto.java
  src/main/java/com/travelland/dto/TripSearchDto.java
  src/main/java/com/travelland/dto/UnitPlanDto.java
  src/main/java/com/travelland/global/config/SwaggerConfig.java
  src/main/java/com/travelland/global/config/WebConfig.java
  src/main/java/com/travelland/global/config/WebSecurityConfig.java
  src/main/java/com/travelland/repository/es/CustomTripRepository.java
  src/main/java/com/travelland/repository/es/CustomTripRepositoryImpl.java
  src/main/java/com/travelland/repository/plan/PlanRepository.java
  src/main/java/com/travelland/repository/plan/querydsl/CustomPlanRepository.java
  src/main/java/com/travelland/repository/plan/querydsl/CustomPlanRepositoryImpl.java
  src/main/java/com/travelland/repository/trip/TripHashtagRepository.java
  src/main/java/com/travelland/repository/trip/TripImageRepository.java
  src/main/java/com/travelland/repository/trip/TripLikeRepository.java
  src/main/java/com/travelland/repository/trip/TripRepository.java
  src/main/java/com/travelland/repository/trip/TripScrapRepository.java
  src/main/java/com/travelland/repository/trip/TripSearchRepository.java
  src/main/java/com/travelland/repository/trip/querydsl/CustomTripLikeRepository.java
  src/main/java/com/travelland/repository/trip/querydsl/CustomTripLikeRepositoryImpl.java
  src/main/java/com/travelland/repository/trip/querydsl/CustomTripRepositoryV2.java
  src/main/java/com/travelland/repository/trip/querydsl/CustomTripRepositoryV2Impl.java
  src/main/java/com/travelland/repository/trip/querydsl/CustomTripScrapRepository.java
  src/main/java/com/travelland/repository/trip/querydsl/CustomTripScrapRepositoryImpl.java
  src/main/java/com/travelland/service/plan/PlanService.java
  src/main/java/com/travelland/service/trip/TripImageService.java
  src/main/java/com/travelland/service/trip/TripLikeService.java
  src/main/java/com/travelland/service/trip/TripScrapService.java
  src/main/java/com/travelland/service/trip/TripSearchService.java
  src/main/java/com/travelland/service/trip/TripService.java
  src/main/resources/keystore.p12
  src/main/resources/static/es-mapping.json
  src/test/java/com/travelland/service/KakaoServiceTest.java
  src/test/java/com/travelland/service/plan/PlanServiceTest.java
  src/test/java/com/travelland/service/trip/TripServiceTest.java
Labels: documentation

#43 Features/signout
  src/main/java/com/travelland/controller/MemberController.java
  src/main/java/com/travelland/docs/MemberControllerDocs.java
  src/main/java/com/travelland/domain/member/Member.java
  src/main/java/com/travelland/domain/member/MemberEntityListener.java
  src/main/java/com/travelland/domain/member/MemberHistory.java
  src/main/java/com/travelland/domain/member/RefreshToken.java
  src/main/java/com/travelland/domain/plan/Plan.java
  src/main/java/com/travelland/domain/plan/PlanLike.java
  src/main/java/com/travelland/domain/plan/PlanScrap.java
  src/main/java/com/travelland/domain/trip/Trip.java
  src/main/java/com/travelland/domain/trip/TripLike.java
  src/main/java/com/travelland/domain/trip/TripScrap.java
  src/main/java/com/travelland/dto/MemberDto.java
  src/main/java/com/travelland/global/config/WebConfig.java
  src/main/java/com/travelland/global/config/WebSecurityConfig.java
  src/main/java/com/travelland/global/jwt/JwtUtil.java
  src/main/java/com/travelland/global/security/JwtAuthorizationFilter.java
  src/main/java/com/travelland/global/security/UserDetailsImpl.java
  src/main/java/com/travelland/global/security/UserDetailsServiceImpl.java
  src/main/java/com/travelland/global/support/BeanUtils.java
  src/main/java/com/travelland/repository/member/MemberHistoryRepository.java
  src/main/java/com/travelland/repository/member/MemberRepository.java
  src/main/java/com/travelland/repository/member/RefreshTokenRepository.java
  src/main/java/com/travelland/repository/plan/PlanLikeRepository.java
  src/main/java/com/travelland/repository/plan/PlanScrapRepository.java
  src/main/java/com/travelland/repository/plan/querydsl/CustomPlanLikeRepository.java
  src/main/java/com/travelland/repository/plan/querydsl/CustomPlanLikeRepositoryImpl.java
  src/main/java/com/travelland/repository/plan/querydsl/CustomPlanScrapRepository.java
  src/main/java/com/travelland/repository/plan/querydsl/CustomPlanScrapRepositoryImpl.java
  src/main/java/com/travelland/repository/trip/TripLikeRepository.java
  src/main/java/com/travelland/repository/trip/TripScrapRepository.java
  src/main/java/com/travelland/repository/trip/querydsl/CustomTripLikeRepository.java
  src/main/java/com/travelland/repository/trip/querydsl/CustomTripLikeRepositoryImpl.java
  src/main/java/com/travelland/repository/trip/querydsl/CustomTripRepositoryV2.java
  src/main/java/com/travelland/repository/trip/querydsl/CustomTripRepositoryV2Impl.java
  src/main/java/com/travelland/repository/trip/querydsl/CustomTripScrapRepository.java
  src/main/java/com/travelland/repository/trip/querydsl/CustomTripScrapRepositoryImpl.java
  src/main/java/com/travelland/service/KakaoService.java
  src/main/java/com/travelland/service/MemberService.java
  src/main/java/com/travelland/service/plan/PlanLikeService.java
  src/main/java/com/travelland/service/plan/PlanScrapService.java
  src/main/java/com/travelland/service/plan/PlanService.java
  src/main/java/com/travelland/service/trip/TripLikeService.java
  src/main/java/com/travelland/service/trip/TripScrapService.java
  src/main/java/com/travelland/service/trip/TripService.java
Labels: enhancement

#47 REFACTOR: 데이터 타입, 네이밍 수정
  src/main/java/com/travelland/controller/TripController.java
  src/main/java/com/travelland/controller/TripSearchController.java
  src/main/java/com/travelland/docs/TripControllerDocs.java
  src/main/java/com/travelland/document/TripSearchDoc.java
  src/main/java/com/travelland/domain/trip/Trip.java
  src/main/java/com/travelland/domain/trip/TripHashtag.java
  src/main/java/com/travelland/domain/trip/TripImage.java
  src/main/java/com/travelland/dto/TripDto.java
  src/main/java/com/travelland/dto/TripSearchDto.java
  src/main/java/com/travelland/repository/es/CustomTripRepository.java
  src/main/java/com/travelland/repository/es/CustomTripRepositoryImpl.java
  src/main/java/com/travelland/repository/trip/TripHashtagRepository.java
  src/main/java/com/travelland/repository/trip/TripImageRepository.java
  src/main/java/com/travelland/repository/trip/TripLikeRepository.java
  src/main/java/com/travelland/repository/trip/TripRepository.java
  src/main/java/com/travelland/repository/trip/TripScrapRepository.java
  src/main/java/com/travelland/repository/trip/TripSearchRepository.java
  src/main/java/com/travelland/repository/trip/querydsl/CustomTripImageRepository.java
  src/main/java/com/travelland/repository/trip/querydsl/CustomTripImageRepositoryImpl.java
  src/main/java/com/travelland/repository/trip/querydsl/CustomTripLikeRepository.java
  src/main/java/com/travelland/repository/trip/querydsl/CustomTripLikeRepositoryImpl.java
  src/main/java/com/travelland/repository/trip/querydsl/CustomTripRepositoryV2Impl.java
  src/main/java/com/travelland/repository/trip/querydsl/CustomTripScrapRepository.java
  src/main/java/com/travelland/repository/trip/querydsl/CustomTripScrapRepositoryImpl.java
  src/main/java/com/travelland/service/trip/TripImageService.java
  src/main/java/com/travelland/service/trip/TripLikeService.java
  src/main/java/com/travelland/service/trip/TripScrapService.java
  src/main/java/com/travelland/service/trip/TripSearchService.java
  src/main/java/com/travelland/service/trip/TripService.java
  src/main/resources/static/es-mapping.json
  src/test/java/com/travelland/service/trip/TripServiceTest.java
Labels: enhancement

#49 Features/notify
  src/main/java/com/travelland/constant/TripLocation.java
  src/main/java/com/travelland/controller/MemberController.java
  src/main/java/com/travelland/controller/PlanController.java
  src/main/java/com/travelland/controller/TripController.java
  src/main/java/com/travelland/domain/member/Member.java
  src/main/java/com/travelland/domain/plan/DayPlan.java
  src/main/java/com/travelland/domain/plan/Plan.java
  src/main/java/com/travelland/domain/plan/PlanComment.java
  src/main/java/com/travelland/domain/plan/UnitPlan.java
  src/main/java/com/travelland/domain/trip/Trip.java
  src/main/java/com/travelland/domain/trip/TripImage.java
  src/main/java/com/travelland/dto/MemberDto.java
  src/main/java/com/travelland/dto/member/MemberDto.java
  src/main/java/com/travelland/dto/plan/DayPlanDto.java
  src/main/java/com/travelland/dto/plan/PlanCommentDto.java
  src/main/java/com/travelland/dto/plan/PlanDto.java
  src/main/java/com/travelland/dto/plan/UnitPlanDto.java
  src/main/java/com/travelland/dto/trip/TripDto.java
  src/main/java/com/travelland/dto/trip/TripImageDto.java
  src/main/java/com/travelland/esdoc/TripSearchDoc.java
  src/main/java/com/travelland/global/config/RedisConfig.java
  src/main/java/com/travelland/global/config/WebSecurityConfig.java
  src/main/java/com/travelland/global/s3/S3FileService.java
  src/main/java/com/travelland/global/security/JwtAuthorizationFilter.java
  src/main/java/com/travelland/global/security/JwtUtil.java
  src/main/java/com/travelland/repository/member/MemberRepository.java
  src/main/java/com/travelland/repository/plan/querydsl/CustomPlanRepository.java
  src/main/java/com/travelland/repository/plan/querydsl/CustomPlanRepositoryImpl.java
  src/main/java/com/travelland/repository/trip/TripSearchRepository.java
  src/main/java/com/travelland/repository/trip/es/CustomTripRepository.java
  src/main/java/com/travelland/repository/trip/es/CustomTripRepositoryImpl.java
  src/main/java/com/travelland/service/member/KakaoService.java
  src/main/java/com/travelland/service/member/MemberService.java
  src/main/java/com/travelland/service/plan/PlanLikeService.java
  src/main/java/com/travelland/service/plan/PlanScrapService.java
  src/main/java/com/travelland/service/plan/PlanService.java
  src/main/java/com/travelland/service/trip/TripImageService.java
  src/main/java/com/travelland/service/trip/TripLikeService.java
  src/main/java/com/travelland/service/trip/TripScrapService.java
  src/main/java/com/travelland/service/trip/TripSearchService.java
  src/main/java/com/travelland/service/trip/TripService.java
  src/main/java/com/travelland/swagger/MemberControllerDocs.java
  src/main/java/com/travelland/swagger/PlanControllerDocs.java
  src/main/java/com/travelland/swagger/TestControllerDocs.java
  src/main/java/com/travelland/swagger/TripControllerDocs.java
  src/test/java/com/travelland/service/KakaoServiceTest.java
  src/test/java/com/travelland/service/plan/PlanServiceTest.java
  src/test/java/com/travelland/service/trip/TripServiceTest.java
Labels: enhancement

#50 FIX: redis server 이전
  src/main/java/com/travelland/global/config/RedisConfig.java
Labels: enhancement

#58 Features/trip
  .github/workflows/github-actions.yml
  src/main/java/com/travelland/controller/MemberController.java
  src/main/java/com/travelland/controller/PlanController.java
  src/main/java/com/travelland/controller/TripController.java
  src/main/java/com/travelland/domain/plan/DayPlan.java
  src/main/java/com/travelland/domain/plan/Plan.java
  src/main/java/com/travelland/domain/plan/UnitPlan.java
  src/main/java/com/travelland/domain/trip/Trip.java
  src/main/java/com/travelland/domain/trip/TripComment.java
  src/main/java/com/travelland/dto/member/MemberDto.java
  src/main/java/com/travelland/dto/plan/DayPlanDto.java
  src/main/java/com/travelland/dto/plan/PlanDto.java
  src/main/java/com/travelland/dto/plan/UnitPlanDto.java
  src/main/java/com/travelland/dto/trip/TripCommentDto.java
  src/main/java/com/travelland/dto/trip/TripDto.java
  src/main/java/com/travelland/esdoc/TripSearchDoc.java
  src/main/java/com/travelland/global/exception/ErrorCode.java
  src/main/java/com/travelland/global/security/JwtAuthorizationFilter.java
  src/main/java/com/travelland/global/security/JwtUtil.java
  src/main/java/com/travelland/repository/trip/TripCommentRepository.java
  src/main/java/com/travelland/repository/trip/TripRepository.java
  src/main/java/com/travelland/repository/trip/TripScrapRepository.java
  src/main/java/com/travelland/repository/trip/es/CustomTripRepositoryImpl.java
  src/main/java/com/travelland/repository/trip/querydsl/CustomTripCommentRepository.java
  src/main/java/com/travelland/repository/trip/querydsl/CustomTripCommentRepositoryImpl.java
  src/main/java/com/travelland/repository/trip/querydsl/CustomTripRepositoryV2.java
  src/main/java/com/travelland/repository/trip/querydsl/CustomTripScrapRepositoryImpl.java
  src/main/java/com/travelland/service/member/KakaoService.java
  src/main/java/com/travelland/service/plan/PlanService.java
  src/main/java/com/travelland/service/trip/TripCommentService.java
  src/main/java/com/travelland/service/trip/TripImageService.java
  src/main/java/com/travelland/service/trip/TripLikeService.java
  src/main/java/com/travelland/service/trip/TripScrapService.java
  src/main/java/com/travelland/service/trip/TripSearchService.java
  src/main/java/com/travelland/service/trip/TripService.java
  src/main/java/com/travelland/swagger/MemberControllerDocs.java
  src/main/java/com/travelland/swagger/PlanControllerDocs.java
  src/main/java/com/travelland/swagger/TripControllerDocs.java
  src/main/java/com/travelland/valid/trip/TripValidationGroups.java
  src/main/java/com/travelland/valid/trip/TripValidationSequence.java
  src/main/resources/application.yml
Labels: enhancement

#59 Features/login
  build.gradle
  src/main/java/com/travelland/constant/Gender.java
  src/main/java/com/travelland/controller/MemberController.java
  src/main/java/com/travelland/domain/member/Member.java
  src/main/java/com/travelland/dto/member/MemberDto.java
  src/main/java/com/travelland/dto/member/OAuthAttributes.java
  src/main/java/com/travelland/global/config/WebSecurityConfig.java
  src/main/java/com/travelland/global/security/JwtAuthorizationFilter.java
  src/main/java/com/travelland/global/security/JwtUtil.java
  src/main/java/com/travelland/global/security/OAuth2MemberSuccessHandler.java
  src/main/java/com/travelland/global/security/UserDetailsImpl.java
  src/main/java/com/travelland/service/member/CustomOAuth2UserService.java
  src/main/java/com/travelland/service/member/KakaoService.java
  src/main/java/com/travelland/service/member/MemberService.java
  src/main/java/com/travelland/service/trip/TripCommentService.java
  src/main/java/com/travelland/service/trip/TripService.java
  src/main/java/com/travelland/swagger/MemberControllerDocs.java
  src/main/resources/templates/login.html
Labels: enhancement

#63 Features/cache
  build.gradle
  src/main/java/com/travelland/TravellandApplication.java
  src/main/java/com/travelland/constant/Constants.java
  src/main/java/com/travelland/controller/PlanController.java
  src/main/java/com/travelland/controller/TripController.java
  src/main/java/com/travelland/domain/member/MemberEntityListener.java
  src/main/java/com/travelland/domain/trip/Trip.java
  src/main/java/com/travelland/dto/trip/TripDto.java
  src/main/java/com/travelland/esdoc/TripSearchDoc.java
  src/main/java/com/travelland/global/config/RedisConfig.java
  src/main/java/com/travelland/global/config/RestTemplateConfig.java
  src/main/java/com/travelland/global/elasticsearch/ElasticsearchLogService.java
  src/main/java/com/travelland/global/job/BatchScheduler.java
  src/main/java/com/travelland/global/job/DataSet.java
  src/main/java/com/travelland/global/job/TripRecommendJobConfig.java
  src/main/java/com/travelland/repository/plan/PlanLikeRepository.java
  src/main/java/com/travelland/repository/plan/PlanScrapRepository.java
  src/main/java/com/travelland/repository/plan/querydsl/CustomPlanLikeRepository.java
  src/main/java/com/travelland/repository/plan/querydsl/CustomPlanLikeRepositoryImpl.java
  src/main/java/com/travelland/repository/plan/querydsl/CustomPlanRepository.java
  src/main/java/com/travelland/repository/plan/querydsl/CustomPlanRepositoryImpl.java
  src/main/java/com/travelland/repository/plan/querydsl/CustomPlanScrapRepository.java
  src/main/java/com/travelland/repository/plan/querydsl/CustomPlanScrapRepositoryImpl.java
  src/main/java/com/travelland/repository/trip/TripLikeRepository.java
  src/main/java/com/travelland/repository/trip/TripRepository.java
  src/main/java/com/travelland/repository/trip/TripSearchRepository.java
  src/main/java/com/travelland/repository/trip/es/CustomTripRepository.java
  src/main/java/com/travelland/repository/trip/es/CustomTripRepositoryImpl.java
  src/main/java/com/travelland/repository/trip/querydsl/CustomTripLikeRepository.java
  src/main/java/com/travelland/repository/trip/querydsl/CustomTripLikeRepositoryImpl.java
  src/main/java/com/travelland/repository/trip/querydsl/CustomTripRepositoryV2.java
  src/main/java/com/travelland/repository/trip/querydsl/CustomTripRepositoryV2Impl.java
  src/main/java/com/travelland/service/plan/PlanLikeService.java
  src/main/java/com/travelland/service/plan/PlanScrapService.java
  src/main/java/com/travelland/service/plan/PlanService.java
  src/main/java/com/travelland/service/trip/TripLikeService.java
  src/main/java/com/travelland/service/trip/TripScrapService.java
  src/main/java/com/travelland/service/trip/TripSearchService.java
  src/main/java/com/travelland/service/trip/TripService.java
  src/main/java/com/travelland/swagger/PlanControllerDocs.java
  src/main/java/com/travelland/swagger/TripControllerDocs.java
  src/main/resources/static/es-mapping.json
  src/test/java/com/travelland/service/trip/TripSearchServiceTest.java
  src/test/java/com/travelland/service/trip/TripServiceTest.java
Labels: enhancement

#64 Features/trip
  src/main/java/com/travelland/domain/trip/Trip.java
  src/main/java/com/travelland/dto/trip/TripDto.java
  src/main/java/com/travelland/global/exception/ErrorCode.java
  src/main/java/com/travelland/repository/trip/TripRepository.java
  src/main/java/com/travelland/repository/trip/querydsl/CustomTripRepositoryV2.java
  src/main/java/com/travelland/repository/trip/querydsl/CustomTripRepositoryV2Impl.java
  src/main/java/com/travelland/service/trip/TripService.java
Labels: enhancement

#65 Features/batch test
  src/main/java/com/travelland/TravellandApplication.java
  src/main/java/com/travelland/global/job/BatchScheduler.java
  src/main/java/com/travelland/global/job/TripRecommendJobConfig.java
  src/main/java/com/travelland/service/trip/TripService.java
  src/main/resources/application.yml
  src/test/java/com/travelland/service/member/MemberServiceTest.java
  src/test/java/com/travelland/service/trip/TripLikeServiceTest.java
  src/test/java/com/travelland/service/trip/TripSearchServiceTest.java
  src/test/java/com/travelland/service/trip/TripServiceTest.java
Labels: enhancement

#67 Features/serach rank
  build.gradle
  src/main/java/com/travelland/TravellandApplication.java
  src/main/java/com/travelland/controller/TripController.java
  src/main/java/com/travelland/domain/trip/Trip.java
  src/main/java/com/travelland/global/elasticsearch/ElasticsearchLogService.java
  src/main/java/com/travelland/global/job/BatchScheduler.java
  src/main/java/com/travelland/global/job/TripRecommendJobConfig.java
  src/main/java/com/travelland/service/trip/TripSearchService.java
  src/main/java/com/travelland/service/trip/TripService.java
  src/main/java/com/travelland/swagger/TripControllerDocs.java
Labels: enhancement

#70 Features/serach rank
  src/main/java/com/travelland/controller/TripController.java
  src/main/java/com/travelland/dto/trip/TripDto.java
  src/main/java/com/travelland/repository/trip/es/CustomTripRepository.java
  src/main/java/com/travelland/repository/trip/es/CustomTripRepositoryImpl.java
  src/main/java/com/travelland/service/trip/TripSearchService.java
  src/main/java/com/travelland/service/trip/TripService.java
  src/main/java/com/travelland/swagger/TripControllerDocs.java
Labels: enhancement

#72 Features/serach rank
  src/main/java/com/travelland/dto/trip/TripDto.java
  src/main/java/com/travelland/esdoc/TripSearchDoc.java
  src/main/java/com/travelland/repository/trip/es/CustomTripRepositoryImpl.java
  src/main/java/com/travelland/service/trip/TripService.java
Labels: enhancement

#74 Features/serach rank
  src/main/java/com/travelland/constant/Constants.java
  src/main/java/com/travelland/controller/TripController.java
  src/main/java/com/travelland/domain/trip/TripArea.java
  src/main/java/com/travelland/dto/trip/TripDto.java
  src/main/java/com/travelland/esdoc/TripSearchDoc.java
  src/main/java/com/travelland/repository/trip/es/CustomTripRepository.java
  src/main/java/com/travelland/repository/trip/es/CustomTripRepositoryImpl.java
  src/main/java/com/travelland/service/trip/TripSearchService.java
  src/main/java/com/travelland/service/trip/TripService.java
Labels: enhancement

#75 Features/serach rank
  src/main/java/com/travelland/constant/Constants.java
  src/main/java/com/travelland/domain/trip/TripArea.java
  src/main/java/com/travelland/repository/trip/TripRepository.java
  src/main/java/com/travelland/repository/trip/es/CustomTripRepository.java
  src/main/java/com/travelland/repository/trip/es/CustomTripRepositoryImpl.java
  src/main/java/com/travelland/service/trip/TripSearchService.java
  src/main/java/com/travelland/service/trip/TripService.java
Labels: enhancement

#76 FIX: 좋아요/스크랩 여부 확인 코드 수정
  src/main/java/com/travelland/repository/trip/TripLikeRepository.java
  src/main/java/com/travelland/repository/trip/TripScrapRepository.java
  src/main/java/com/travelland/service/trip/TripLikeService.java
  src/main/java/com/travelland/service/trip/TripScrapService.java
Labels: bug

#77 Features/serach rank
  src/main/java/com/travelland/constant/Constants.java
  src/main/java/com/travelland/service/trip/TripService.java
Labels: bug

#78 Fix: 좋아요/스크랩 및 비로그인 관련 로직 수정
  src/main/java/com/travelland/repository/plan/PlanLikeRepository.java
  src/main/java/com/travelland/repository/plan/PlanScrapRepository.java
  src/main/java/com/travelland/service/plan/PlanLikeService.java
  src/main/java/com/travelland/service/plan/PlanScrapService.java
  src/main/java/com/travelland/service/plan/PlanService.java
  src/main/java/com/travelland/swagger/PlanControllerDocs.java
Labels: bug

#83 fix: area 매핑 정보 추가
  src/main/java/com/travelland/constant/Constants.java
Labels: bug

#85 FEAT: 썸네일 이미지 리사이즈 기능 추가
  src/main/java/com/travelland/global/s3/S3FileService.java
  src/main/java/com/travelland/repository/trip/TripImageRepository.java
  src/main/java/com/travelland/service/trip/TripImageService.java
  src/main/java/com/travelland/service/trip/TripService.java
Labels: enhancement

#87 Hotfix/trip image
  src/main/java/com/travelland/global/s3/S3FileService.java
  src/main/java/com/travelland/service/trip/TripImageService.java
Labels: bug

#88 마이페이지 테스트 API 추가
  src/main/java/com/travelland/controller/TestTripController.java
  src/main/java/com/travelland/controller/TripController.java
  src/main/java/com/travelland/dto/trip/TripDto.java
  src/main/java/com/travelland/repository/trip/TripRepository.java
  src/main/java/com/travelland/repository/trip/TripScrapRepository.java
  src/main/java/com/travelland/service/trip/TestTripService.java
  src/main/java/com/travelland/service/trip/TripService.java
  src/main/java/com/travelland/swagger/TestControllerDocs.java
  src/main/java/com/travelland/swagger/TestTripControllerDocs.java
Labels: enhancement

#90 여행후기 코드 수정 및 마이페이지 조회 API 추가
  src/main/java/com/travelland/controller/MemberController.java
  src/main/java/com/travelland/controller/TripController.java
  src/main/java/com/travelland/dto/member/MemberDto.java
  src/main/java/com/travelland/dto/trip/TripDto.java
  src/main/java/com/travelland/service/member/MemberService.java
  src/main/java/com/travelland/service/trip/TripLikeService.java
  src/main/java/com/travelland/service/trip/TripScrapService.java
  src/main/java/com/travelland/service/trip/TripService.java
  src/main/java/com/travelland/swagger/MemberControllerDocs.java
Labels: enhancement

#94 Features/area edit
  build.gradle
  src/main/java/com/travelland/constant/Constants.java
  src/main/java/com/travelland/controller/TripController.java
  src/main/java/com/travelland/domain/search/HangleAnalyzer.java
  src/main/java/com/travelland/domain/search/KoreanKeyboardToEng.java
  src/main/java/com/travelland/domain/search/SearchArea.java
  src/main/java/com/travelland/domain/trip/TripArea.java
  src/main/java/com/travelland/esdoc/TripRecommendDoc.java
  src/main/java/com/travelland/esdoc/TripSearchDoc.java
  src/main/java/com/travelland/global/job/TripRecommendJobConfig.java
  src/main/java/com/travelland/repository/trip/TripRecommendRepository.java
  src/main/java/com/travelland/repository/trip/TripSearchRepository.java
  src/main/java/com/travelland/repository/trip/es/CustomTripRecommendRepository.java
  src/main/java/com/travelland/repository/trip/es/CustomTripRecommendRepositoryImpl.java
  src/main/java/com/travelland/repository/trip/es/CustomTripSearchRepository.java
  src/main/java/com/travelland/repository/trip/es/CustomTripSearchRepositoryImpl.java
  src/main/java/com/travelland/service/trip/TripSearchService.java
  src/main/resources/static/es-mapping.json
  src/main/resources/static/es-setting.json
  src/test/java/com/travelland/service/trip/TripSearchServiceTest.java
Labels: enhancement

#95 Features/area edit
  src/main/java/com/travelland/domain/search/KoreanKeyboardToEng.java
  src/main/java/com/travelland/service/trip/TripSearchService.java
  src/test/java/com/travelland/service/trip/TripSearchServiceTest.java
Labels: bug

#96 Fix: 유저 인증 확인 추가
  src/main/java/com/travelland/controller/TripController.java
Labels: bug

#97 Features/my trip fix
  src/main/java/com/travelland/global/elasticsearch/ElasticsearchLogService.java
  src/main/java/com/travelland/global/job/BatchScheduler.java
  src/main/java/com/travelland/global/job/DataSet.java
  src/main/java/com/travelland/global/job/TripRecommendJobConfig.java
  src/main/java/com/travelland/service/trip/TripSearchService.java
Labels: bug

#98 이미지 업로드 병렬 처리 코드 추가
  src/main/java/com/travelland/controller/TestTripController.java
  src/main/java/com/travelland/global/config/AsyncConfig.java
  src/main/java/com/travelland/service/trip/TestTripService.java
  src/main/java/com/travelland/service/trip/TripImageService.java
  src/main/java/com/travelland/swagger/TestTripControllerDocs.java
Labels: enhancement

#99 FIX: 게시글 이미지 저장 에러 수정
  src/main/java/com/travelland/service/trip/TripImageService.java
  src/main/java/com/travelland/service/trip/TripService.java
Labels: bug

#101 Features/notify
  src/main/java/com/travelland/constant/NotificationType.java
  src/main/java/com/travelland/controller/MemberController.java
  src/main/java/com/travelland/controller/NotificationController.java
  src/main/java/com/travelland/domain/Notification.java
  src/main/java/com/travelland/domain/plan/PlanInvite.java
  src/main/java/com/travelland/dto/NotificationDto.java
  src/main/java/com/travelland/dto/plan/PlanDto.java
  src/main/java/com/travelland/global/config/RedisConfig.java
  src/main/java/com/travelland/global/notification/DoEvent.java
  src/main/java/com/travelland/global/notification/NotificationSender.java
  src/main/java/com/travelland/global/notification/Publisher.java
  src/main/java/com/travelland/repository/member/MemberRepository.java
  src/main/java/com/travelland/repository/notification/EmitterRepository.java
  src/main/java/com/travelland/repository/notification/EmitterRepositoryImpl.java
  src/main/java/com/travelland/repository/plan/PlanInviteRepository.java
  src/main/java/com/travelland/service/member/MemberService.java
  src/main/java/com/travelland/service/notification/NotificationService.java
  src/main/java/com/travelland/service/notification/Subscriber.java
  src/main/java/com/travelland/service/plan/PlanInviteService.java
  src/main/java/com/travelland/swagger/MemberControllerDocs.java
  src/test/java/com/travelland/repository/EmitterRepositoryImplTest.java
  src/test/java/com/travelland/service/NotificationServiceTest.java
Labels: enhancement

#103 Features/notify
  src/main/java/com/travelland/controller/NotificationController.java
  src/main/java/com/travelland/controller/PlanController.java
  src/main/java/com/travelland/swagger/NotificationControllerDocs.java
Labels: documentation

#104 Features/my trip fix
  src/main/java/com/travelland/esdoc/TripRecommendDoc.java
  src/main/java/com/travelland/esdoc/TripSearchDoc.java
  src/main/java/com/travelland/service/trip/TripSearchService.java
  src/test/java/com/travelland/service/trip/TripSearchServiceTest.java
Labels: bug

#107 여행후기 수정하기 코드 리팩토링 및 javadoc 작성
  src/main/java/com/travelland/controller/TripController.java
  src/main/java/com/travelland/domain/trip/Trip.java
  src/main/java/com/travelland/dto/trip/TripCommentDto.java
  src/main/java/com/travelland/dto/trip/TripDto.java
  src/main/java/com/travelland/dto/trip/TripImageDto.java
  src/main/java/com/travelland/esdoc/TripSearchDoc.java
  src/main/java/com/travelland/global/s3/S3FileService.java
  src/main/java/com/travelland/repository/trip/TripCommentRepository.java
  src/main/java/com/travelland/repository/trip/TripImageRepository.java
  src/main/java/com/travelland/repository/trip/TripLikeRepository.java
  src/main/java/com/travelland/repository/trip/TripRepository.java
  src/main/java/com/travelland/repository/trip/TripScrapRepository.java
  src/main/java/com/travelland/repository/trip/querydsl/CustomTripCommentRepositoryImpl.java
  src/main/java/com/travelland/repository/trip/querydsl/CustomTripImageRepository.java
  src/main/java/com/travelland/repository/trip/querydsl/CustomTripImageRepositoryImpl.java
  src/main/java/com/travelland/repository/trip/querydsl/CustomTripLikeRepositoryImpl.java
  src/main/java/com/travelland/repository/trip/querydsl/CustomTripRepositoryV2.java
  src/main/java/com/travelland/repository/trip/querydsl/CustomTripRepositoryV2Impl.java
  src/main/java/com/travelland/repository/trip/querydsl/CustomTripScrapRepositoryImpl.java
  src/main/java/com/travelland/service/trip/TripCommentService.java
  src/main/java/com/travelland/service/trip/TripImageService.java
  src/main/java/com/travelland/service/trip/TripLikeService.java
  src/main/java/com/travelland/service/trip/TripScrapService.java
  src/main/java/com/travelland/service/trip/TripService.java
  src/test/java/com/travelland/service/trip/TripLikeServiceTest.java
  src/test/java/com/travelland/service/trip/TripServiceTest.java
Labels: bug, enhancement

#108 Features/total search fix
  src/main/java/com/travelland/TravellandApplication.java
  src/main/java/com/travelland/domain/search/KoreanKeyboardToEng.java
  src/main/java/com/travelland/dto/trip/TripDto.java
  src/main/java/com/travelland/global/elasticsearch/ElasticsearchLogService.java
  src/main/java/com/travelland/global/job/BatchScheduler.java
  src/main/java/com/travelland/global/job/DataSet.java
  src/main/java/com/travelland/global/job/TripRecommendJobConfig.java
  src/main/java/com/travelland/service/trip/TripSearchService.java
  src/test/java/com/travelland/service/trip/TripSearchServiceTest.java
Labels: bug

#109 Features/notify
  src/main/java/com/travelland/controller/NotificationController.java
  src/main/java/com/travelland/domain/Notification.java
  src/main/java/com/travelland/dto/NotificationDto.java
  src/main/java/com/travelland/repository/notification/EmitterRepository.java
  src/main/java/com/travelland/repository/notification/EmitterRepositoryImpl.java
  src/main/java/com/travelland/repository/notification/NotificationRepository.java
  src/main/java/com/travelland/service/notification/NotificationService.java
  src/main/java/com/travelland/service/notification/Subscriber.java
  src/main/java/com/travelland/service/plan/PlanInviteService.java
  src/main/java/com/travelland/swagger/NotificationControllerDocs.java
  src/test/java/com/travelland/repository/EmitterRepositoryImplTest.java
Labels: bug

#110 CMYK 타입 이미지 리사이즈 에러 해결
  build.gradle
  src/main/java/com/travelland/global/s3/S3FileService.java
  src/test/java/com/travelland/global/s3/S3FileServiceTest.java
  src/test/resources/static/img/test.png
Labels: bug
